# Generated by Django 3.2 on 2021-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('iiif_url_root', models.URLField()),
            ],
        ),
    ]
