# Generated by Django 3.2 on 2021-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_name',
            field=models.CharField(default='Wellcome Collection', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
