# Generated by Django 3.2 on 2021-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_institution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='api_root',
            field=models.URLField(default='https://api.wellcomecollection.org/catalogue/v2/images'),
            preserve_default=False,
        ),
    ]
