# Generated by Django 3.2 on 2021-04-14 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digital_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapbook_creator', to=settings.AUTH_USER_MODEL)),
                ('digital_images', models.ManyToManyField(related_name='scrapbooks', to='digital_images.DigitalImage')),
            ],
        ),
    ]
