# Generated by Django 3.2 on 2021-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0002_auto_20210414_1629'),
        ('scrapbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='digital_images',
            field=models.ManyToManyField(blank=True, related_name='scrapbooks', to='digital_images.DigitalImage'),
        ),
    ]
