# Generated by Django 3.2 on 2021-04-14 16:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_institution_api_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_image', models.URLField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('origin_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_images', to='institutions.institution')),
            ],
        ),
    ]
