# Generated by Django 3.2 on 2021-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalimage',
            name='catalogue_title',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalimage',
            name='work_type',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
