# Generated by Django 3.2 on 2021-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0002_auto_20210414_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalimage',
            name='digital_image',
        ),
        migrations.AddField(
            model_name='digitalimage',
            name='catalogue_image_id',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalimage',
            name='digital_image_id',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
