# Generated by Django 3.2 on 2021-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0003_auto_20210414_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalimage',
            name='digital_image_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
