# Generated by Django 3.2 on 2021-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0005_digitalimage_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalimage',
            name='catalogue_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='digitalimage',
            name='work_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
