# Generated by Django 3.2 on 2021-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_images', '0006_auto_20210415_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalimage',
            name='iiif_manifest',
            field=models.URLField(blank=True),
        ),
    ]
